/*
 * Venue & hotspot API
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using GeoARIt.Api.Model;
using System;
using System.Collections.Generic;

namespace Web.Models
{
    public class VenueHotspotsViewModel
    {
        public Guid VenueGuid { get; set; }
        public Venue Venue { get; set; }
        public IList<Hotspot> Hotspots { get; set; }

        public string VenueTitle
        {
            get
            {
                return Venue == null ? VenueGuid.ToString() : Venue.Name;
            }
        }
    }
}